<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 16.12.18
 * Time: 21:35
 */

namespace App\Tests;


use Symfony\Bundle\FrameworkBundle\Client;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class FullTaskFlowTest extends WebTestCase
{
    /**
     * @var Client
     */
    protected $client;

    /**
     * @var String
     */
    protected $token;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();

        $this->client->request(
            'POST',
            '/api/login_check',
            [],
            [],
            [
                'HTTP_ACCEPT' => 'application/json',
                'CONTENT_TYPE' => 'application/json',
            ],
            json_encode(['username' => 'alex', 'password' => 'alex'])
        );
        $this->token = 'Bearer ' . json_decode($this->client->getResponse()->getContent())->token;
    }

    public function testPostTaskReturnId()
    {
        $data = [
            "content" => "first test task1",
            "completed" => false,
            "created_at" => "2011-12-05T12:00:00+02:00"
        ];
        $this->client->request(
            'POST',
            '/api/task',
            [],
            [],
            [
                'HTTP_JWT_AUTHORIZATION' => $this->token,
                'HTTP_ACCEPT' => 'application/json',
                'CONTENT_TYPE' => 'application/json',
            ],
            json_encode($data)
        );
        $response = $this->client->getResponse();

        $this->assertTrue($response->isSuccessful());
        $this->assertEquals(201, $response->getStatusCode());
        $this->assertJson($response->getContent());

        $obj = json_decode($response->getContent());
        $this->assertEquals("ok", $obj->status);
        $this->assertNotEmpty($obj->id);

        $data['id'] = $obj->id;
        return $data;
    }

    /**
     * @depends testPostTaskReturnId
     */
    public function testGetTask($data) {
        $this->client->request(
            'get',
            '/api/task/'.$data['id'],
            [],
            [],
            [
                'HTTP_JWT_AUTHORIZATION' => $this->token,
                'HTTP_ACCEPT' => 'application/json',
                'CONTENT_TYPE' => 'application/json',
            ]
        );
        $response = $this->client->getResponse();

        $this->assertTrue($response->isSuccessful());
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertJson($response->getContent());

        $this->assertJsonStringEqualsJsonString(json_encode($data), $response->getContent());

        return $data;
    }

    /**
     * @depends testGetTask
     */
    public function testPutTask($data) {
        $data['content'] = 'some new content';

        $this->client->request(
            'PUT',
            '/api/task/'.$data['id'],
            [],
            [],
            [
                'HTTP_JWT_AUTHORIZATION' => $this->token,
                'HTTP_ACCEPT' => 'application/json',
                'CONTENT_TYPE' => 'application/json',
            ],
            json_encode(array_diff_key($data, ['id' => true]))
        );
        $response = $this->client->getResponse();

        $this->assertTrue($response->isSuccessful());
        $this->assertEquals(204, $response->getStatusCode());

        return $data;
    }

    /**
     * @depends testPutTask
     */
    public function testGetUpdatedTask($data) {
        $this->client->request(
            'get',
            '/api/task/'.$data['id'],
            [],
            [],
            [
                'HTTP_JWT_AUTHORIZATION' => $this->token,
                'HTTP_ACCEPT' => 'application/json',
                'CONTENT_TYPE' => 'application/json',
            ]
        );
        $response = $this->client->getResponse();

        $this->assertTrue($response->isSuccessful());
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertJson($response->getContent());

        $this->assertJsonStringEqualsJsonString(json_encode($data), $response->getContent());

        return $data;
    }


}