#index:
#    path: /
#    controller: App\Controller\DefaultController::index
tasks:
    type:     rest
    resource: App\Controller\TaskController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"